# Generated by Django 4.0.4 on 2022-08-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ratingstar_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='products',
        ),
    ]
