# Generated by Django 4.0.4 on 2022-08-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_product_rating_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='products',
            new_name='product',
        ),
    ]
