# Generated by Django 4.0.4 on 2022-08-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_products_rating_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
