# Generated by Django 4.0.4 on 2022-08-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ratingstar_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
